[alembic]
script_location = %(here)s/src/app/migrations
prepend_sys_path = .
path_separator = os

# Named configurations for each module.
# Use `alembic -n <name>` to target a specific module.
databases = platform, identity, parcel, topography, infrastructure, climate

[platform]
version_locations = ./src/app/migrations/versions/platform
script_location = ./src/app/migrations

[identity]
version_locations = ./src/app/migrations/versions/identity
script_location = ./src/app/migrations

[parcel]
version_locations = ./src/app/migrations/versions/parcel
script_location = ./src/app/migrations

[topography]
version_locations = ./src/app/migrations/versions/topography
script_location = ./src/app/migrations

[infrastructure]
version_locations = ./src/app/migrations/versions/infrastructure
script_location = ./src/app/migrations

[climate]
version_locations = ./src/app/migrations/versions/climate
script_location = ./src/app/migrations
