services:
  app:
    build:
      context: .
      target: runtime
      args:
        UV_SYNC_ARGS: "--no-dev"
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    command: >
      granian
      --host=0.0.0.0
      --port=${APP_PORT:-8000}
      --interface=asgi
      --factory
      app.interface.http.asgi:create_asgi_application
