[tool.towncrier]
directory = "changelog.d"
filename = "docs/changelog.md"
title_format = "## [{version}](https://github.com/LandSight/backend/releases/tag/{version}) - {project_date}"
issue_format = "[#{issue}](https://github.com/LandSight/backend/issues/{issue})"

[[tool.towncrier.type]]
name = "Feature"
directory = "feat"
showcontent = true

[[tool.towncrier.type]]
name = "Bugfix"
directory = "bugfix"
showcontent = true

[[tool.towncrier.type]]
name = "Security"
directory = "security"
showcontent = true

[[tool.towncrier.type]]
name = "Deprecation"
directory = "deprecation"
showcontent = true

[[tool.towncrier.type]]
name = "Removal"
directory = "removal"
showcontent = true

[[tool.towncrier.type]]
name = "Docs"
directory = "docs"
showcontent = true

[[tool.towncrier.type]]
name = "Ops"
directory = "ops"
showcontent = true
