"""Add parcel parcels table.

Revision ID: 15c4a02c5334
Revises:
Create Date: 2026-07-15 11:14:47.918714

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import geoalchemy2
import sqlalchemy as sa
from alembic import op


if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "15c4a02c5334"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcels",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "polygon",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
            comment="PostGIS Polygon geometry in SRID 4326 (WGS 84)",
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False, comment="ID of the user who owns this parcel"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["identity.users.id"], name=op.f("fk_parcels_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parcels")),
        schema="parcel",
    )
    # PostGIS automatically creates a GIST index on Geometry columns,
    # so we use IF NOT EXISTS to avoid duplicate index errors.
    op.execute("CREATE INDEX IF NOT EXISTS idx_parcels_polygon ON parcel.parcels USING gist (polygon)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_parcels_polygon", table_name="parcels", schema="parcel", postgresql_using="gist")
    op.drop_table("parcels", schema="parcel")
    # ### end Alembic commands ###
