name: "Lint"

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/lint.yaml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/lint.yaml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.17"
          enable-cache: true

      - name: "Install Python"
        run: uv python install

      - name: "Run lint checks"
        run: make lint

      - name: "Run ruff checks"
        run: |
          uv run ruff check --preview --output-format=github
          uv run ruff format --check --preview --output-format=github

      - name: "Run ty checks"
        run: uv run ty check --output-format=github
