name: "Test"
on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/test.yaml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/test.yaml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Install uv"
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.17"
          enable-cache: true

      - name: "Install Python"
        run: uv python install

      - name: "Run tests"
        run: make test
